<<<<<<< HEAD
name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
=======
name: run junit tests

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

>>>>>>> origin/master
    steps:
      - name: Checkout
        uses: actions/checkout@v1

<<<<<<< HEAD
      - name: Set up JDK 1.17
=======
      - name: Set up JDK 1.11
>>>>>>> origin/master
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

<<<<<<< HEAD
      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Run the unit tests
=======
      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
>>>>>>> origin/master
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
<<<<<<< HEAD

      - name: Build and push the image
        run: |
          docker login --username daeaker --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/daeaker/coffee-order:latest --file Dockerfile .  
          docker push ghcr.io/daeaker/coffee-order:latest
=======
>>>>>>> origin/master
